# Generated by Django 5.0.3 on 2024-03-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_cardanswer_usercardanswer_delete_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='upload_by_userId',
        ),
        migrations.AddField(
            model_name='card',
            name='upload_by_userName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
