# Generated by Django 5.0.3 on 2024-03-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_remove_card_upload_by_userid_card_upload_by_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.CharField(default='', max_length=500, verbose_name='text'),
        ),
    ]
