# Generated by Django 5.0.3 on 2024-03-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_image_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_source',
        ),
        migrations.RemoveField(
            model_name='card',
            name='lan_origin',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='', upload_to='card', verbose_name='image of the card'),
        ),
        migrations.AddField(
            model_name='card',
            name='lan',
            field=models.CharField(choices=[('NL', 'Dutch'), ('EN', 'English'), ('CN', 'Chinese')], default='', max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='text extration of the image'),
        ),
    ]
