# Generated by Django 5.0.3 on 2024-03-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_remove_card_image_source_remove_card_lan_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='', upload_to='media/card', verbose_name='image of the card'),
        ),
    ]
