# Generated by Django 5.0.3 on 2024-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='', upload_to='card', verbose_name='image of the card'),
        ),
    ]
