# Generated by Django 4.2.11 on 2024-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_alter_usercardanswer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='lan',
            field=models.CharField(choices=[('nl', 'Dutch'), ('en', 'English'), ('cn', 'Chinese'), ('it', 'Italian')], default='', max_length=2, verbose_name='language'),
        ),
    ]
