# Generated by Django 5.0.3 on 2024-04-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='comment'),
        ),
    ]
