# Generated by Django 5.0.3 on 2024-04-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_alter_card_lan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercardanswer',
            name='answer',
            field=models.CharField(choices=[('FL', 'flash'), ('DN', 'done'), ('PA', 'pass')], max_length=2),
        ),
    ]
