# Generated by Django 5.0.3 on 2024-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_alter_usercardanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='lan',
            field=models.CharField(choices=[('nl', 'Dutch'), ('cn', 'Chinese'), ('it', 'Italian'), ('fr', 'French')], default='', max_length=2, verbose_name='language'),
        ),
    ]
