# Generated by Django 5.0.3 on 2024-04-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_alter_card_lan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.AddField(
            model_name='card',
            name='original_image',
            field=models.ImageField(default='', upload_to='card', verbose_name='original image'),
        ),
        migrations.AddField(
            model_name='card',
            name='png_image',
            field=models.ImageField(default='', upload_to='card', verbose_name='png version of the image'),
        ),
    ]
