# Generated by Django 5.0.3 on 2024-04-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0019_alter_card_png_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='card',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
    ]
