# Generated by Django 5.0.3 on 2024-04-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0020_alter_card_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='png_image',
            field=models.ImageField(blank=True, default='', upload_to='card', verbose_name='png image'),
        ),
    ]
