# Generated by Django 5.0.3 on 2024-04-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0021_alter_card_png_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='png_image_exist',
            field=models.BooleanField(default=False, verbose_name='png image exist'),
        ),
    ]
