# Generated by Django 5.0.3 on 2024-04-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0022_card_png_image_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='png_image',
            field=models.ImageField(blank=True, default='', upload_to='png', verbose_name='png image'),
        ),
    ]
