# Generated by Django 5.0.3 on 2024-05-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0023_alter_card_png_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to='thumbnail', verbose_name='thubmnail image'),
        ),
        migrations.AddField(
            model_name='card',
            name='thumbnail_exist',
            field=models.BooleanField(default=False, verbose_name='thumbnail image exist'),
        ),
    ]
