# Generated by Django 5.0.3 on 2024-04-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0014_card_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTranslator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_text', models.CharField(default='', max_length=1000)),
                ('tokens', models.JSONField(default=list)),
                ('tokens_translated', models.JSONField(default=list)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='card.card')),
            ],
        ),
    ]
