# Generated by Django 5.0.3 on 2024-04-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttranslator',
            name='tokens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='texttranslator',
            name='tokens_translated',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='texttranslator',
            name='translated_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
