# Generated by Django 5.0.3 on 2024-04-08 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_alter_texttranslator_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttranslator',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 8, 14, 21, 42, 280038), verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='texttranslator',
            name='modification_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 8, 14, 21, 42, 280038), verbose_name='date modified'),
        ),
    ]
