# Generated by Django 5.0.3 on 2024-04-09 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0009_auto_20240409_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttranslator',
            name='tokens',
        ),
        migrations.AlterField(
            model_name='texttokenizer',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 9, 20, 27, 32, 712727), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='texttokenizer',
            name='modification_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 9, 20, 27, 32, 712727), verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='texttranslator',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 9, 20, 27, 32, 711944), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='texttranslator',
            name='modification_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 9, 20, 27, 32, 711944), verbose_name='date modified'),
        ),
    ]
