# Generated by Django 5.0.3 on 2024-04-10 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0012_alter_texttokenizer_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttokenizer',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 10, 15, 18, 57, 986488), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='texttokenizer',
            name='modification_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 10, 15, 18, 57, 986488), verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='texttranslator',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 10, 15, 18, 57, 986280), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='texttranslator',
            name='modification_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 10, 15, 18, 57, 986280), verbose_name='date modified'),
        ),
    ]
