# Generated by Django 4.2.11 on 2024-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(choices=[('8', 'rainbow'), ('7a+', 'mint'), ('7a', 'White'), ('6c+', 'purple'), ('6c', 'red'), ('6b+', 'DarkBlue'), ('6b', 'Yellow'), ('6a+', 'Orange'), ('6a', 'Black'), ('5', 'LightBlue'), ('4', 'Green')], default='4', max_length=3),
        ),
    ]
