# Generated by Django 5.0.3 on 2024-04-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='target_lan',
            field=models.CharField(choices=[('nl', 'Dutch'), ('en', 'English'), ('cn', 'Chinese'), ('it', 'Italian'), ('fr', 'French')], default='', max_length=2),
        ),
    ]
