# Generated by Django 5.0.3 on 2024-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_target_lan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='target_lan',
            field=models.CharField(choices=[('nl', 'Dutch'), ('cn', 'Chinese'), ('it', 'Italian'), ('fr', 'French')], default='', max_length=2),
        ),
    ]
